version: '3'
services:
  products-cli:
    build:
      context: ./.docker/php.cli
    volumes:
      - .:/app
    environment:
      - XDEBUG_CONFIG=remote_host=172.17.0.1 remote_enable=1 remote_autostart=1 remote_port=9020
      - PHP_IDE_CONFIG=serverName=products.cli
